### ISSUE TITLE
Write an endpoint that allows "favoriting" a gallery entry for a logged in user

### ISSUE THREAD

**Issue by luisnaranjo733** [sheared-sasquatch/sparkclips#10]
Need to add a controller action which enables the following kind of AJAX request:

| Http Method        | Url           | Post params|
| ------------- |:-------------:| -----:|
| POST      | /Home/AddFavorite/ | gallery_entry_pk=2 |

OR

| Http Method        | Url           | 
| ------------- |:-------------:| 
| POST      | /Home/AddFavorite/2 

The controller action will need to figure out what the primary key of the currently logged in user is (using identity). If the user is not currently logged in, it should throw an error (maybe a 401 Unauthorized [http status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors)).

Once the controller action has the user pk from the identity session, and the gallery entry primary key from the request (either from the URL or from a http post param), it should create a row in the [GalleryEntry_ApplicationUser ](https://github.com/sheared-sasquatch/sparkclips/blob/master/SparkClips/Models/HairyDatabase/Models.cs#L118) table where GalleryEntryID=2 and ApplicationUserID=4. The existence of this row signals that the user with primary key=4 has favorited the gallery entry with primary key=2 (for example)

**Comment by KyleIWS** [comment]
Luis did this a few weeks ago.
