### ISSUE TITLE
Toggling Favorite Button 

### ISSUE THREAD

**Issue by KyleIWS** [sheared-sasquatch/sparkclips#19]
Given a user who is has favorites on the Gallery page, how do we switch the buttons on the Gallery page to show what they have already been favorited?

 - On page load serverside (GalleryController.cs) attaches an attribute to the entries if they are favorited, which the view (index.cshtml) reads to determine how a button should be rendered.
- After ajax responds with status of favorite request, should refresh the page to update the DOM.

**Comment by luisnaranjo733** [comment]
basically done, except refreshing doesn't work on mobile
