### ISSUE TITLE
[minor] Adding new haircuts doesn't check for valid values in some fields

### ISSUE THREAD

**Issue by greycabb** [sheared-sasquatch/sparkclips#46]
The New Entry page doesn't seem to check for valid values:
__
[Reproduction steps]
1) Create an account
2) Go to "My Haircut Log"
3) Some parameters don't seem to be checked here properly to block bad inputs:
- Cost is allowed to be negative
- You can upload any file types here, like .mp3s and .exes here, when you probably only want pictures

Browser: Google Chrome

**Comment by KyleIWS** [comment]
See reasoning in #45. Users have ability to use haircut log as they desire to achieve value from it. If they input bad values, it will only effect their ability to use it and no one else. Not a feature necessarily, but preventing users from inputting bad information is not in the scope of the haircut log.
