### ISSUE TITLE
Minor: Gallery Navbar Different from the Rest

### ISSUE THREAD

**Issue by jimmybnguyen** [sheared-sasquatch/sparkclips#47]
http://sparkclips.azurewebsites.net/Gallery always uses a hamburger navbar, while the rest of the website uses the standard nav for desktop, and hamburger for mobile. [Issue 36](https://github.com/sheared-sasquatch/sparkclips/issues/36) states that sparkclips will only be supporting mobile, but the gallery navbar and the rest of the website's does not align with this statement.

**Comment by derryc09** [comment]
Hi Jimmy, 

Thanks a lot for your comment. Yes, on a Desktop version of the site, the navbar is expanded as opposed to it being a hamburger menu on the gallery page. However, as we stated in our requirements, we are targeted towards mobile devices at this time. Per our verification, on mobile views, the nav bars are all collapsed as hamburger menus and are not an issue. As such we are closing this issue as we will not be targeting Desktop views at this time. 
Thank you so much!
