### ISSUE TITLE
[Major]: Filter does not apply properly on the gallery

### ISSUE THREAD

**Issue by NgGeorge** [sheared-sasquatch/sparkclips#48]
When I attempt to select different filters and apply them while on the gallery page, the results never change. I have attempted trying every filter option available, but they seem to have no affect on the resulting hairstyles.

Steps for Reproduction : 
1. Open the "Gallery Page"
2. Click the Filter tag icon to open up the filters at the bottom.
3. Select desired filters
4. Apply filters by clicking the "Filter" button

**Comment by luisnaranjo733** [comment]
Fixed by commit 2c9b55d84a40854dcfcf2fd4fee3566867ca9faa
