### ISSUE TITLE
Major: Logs have weird display for various details.

### ISSUE THREAD

**Issue by tgents** [sheared-sasquatch/sparkclips#50]
The main log page is arranged in a grid, but the images get overlapped because they stretch off the page to the left. It seems the height is set appropriately for the grid layout, but the width is way off on my screen.

Also when looking at an individual log, the instructions get cut off and does not save my formatting. I had separated my instructions by new lines but was combined into one line in the detail page.

A few things to note about the log delete. It shows my application user id for some reason, which I don't need to know (could be a potential security issue.) After I delete my log, it redirects me to the detail page of that log despite it being deleted (and shows a not found error because it was deleted). It should ideally redirect me to the logs page.

**Comment by KyleIWS** [comment]
Issue may have been better separated into several issues.

**Image Overlapping**: Unclear on this grid which you mention, picture may be needed to clarify. Width appears perfect in mobile view, which is the scope of app front-facing architecture.

**Log delete**: Application user ID is not needed, however no security threat has been proven to exist so we do not have reason to fix it at this time. ASP Net core has redundancies to prevent any kind of misuse of user IDs. **_WONT FIX_**

**Redirect**: This is addressed in #54  

Will open new issue for formatting of log-entry detail. Closing this one.
