### ISSUE TITLE
[Minor] Haircut name cut off/hidden in detailed view

### ISSUE THREAD

**Issue by lkhwa** [sheared-sasquatch/sparkclips#51]
Minor UI issue: when clicking "View" on any haircut, the h2 heading for the haircut name is hidden underneath your menu bar. Would probably be useful for the user to see this information.

For example, for "Messy Medium for Straight/Wavy Hair", you can see a hint of it here:
<img width="705" alt="screen shot 2017-06-05 at 12 17 41 am" src="https://cloud.githubusercontent.com/assets/22458294/26774301/763b1c08-4984-11e7-884d-6580ed79e9b6.png">

**Comment by Nate-Swanson** [comment]
Added top padding to h2 tag on gallery detail page.
