### ISSUE TITLE
[Major] Account Page Not Setup

### ISSUE THREAD

**Issue by AlexBieg** [sheared-sasquatch/sparkclips#52]
When the user is logged in and accesses their profile page, there are options that are not available and links that are only for developers. 

Reproductions Steps:
1. Click "Log In"
2. Log in to an account
3. Click "Hello <Your Account Name>"
4. On this page both the Phone Number and Two Factor Auth are not setup and only link to articles about how to develop it further on ASP.NET. Also Managing External Logins takes the user to a blank page. 

Suggestions:
Unless your are required to handle External Logins, Phone Numbers, and Two Factor Auth. I would suggest removing those options from that page. That would leave only the change password options, which seems to work fine.

**Comment by Nate-Swanson** [comment]
Removed options other than change password, did not need the additional account management options to satisfy requirements.
