### ISSUE TITLE
[Minor] 'Characteristics' not shown fully in haircut information

### ISSUE THREAD

**Issue by DianaCondon** [sheared-sasquatch/sparkclips#53]
When full screen on a laptop, the first label 'characteristics' not shown fully in Gallery Details.

<img width="1242" alt="screen shot 2017-06-05 at 11 37 36 am" src="https://cloud.githubusercontent.com/assets/10899670/26797922/826dde52-49e3-11e7-9548-9d0115eeecfe.png">

**Comment by derryc09** [comment]
Our solution is targeted towards mobile views. Verified that this stylistic issue exists on a desktop monitor, but NOT on a mobile screen. Closing this as we will not be targetting desktop at this time.
