### ISSUE TITLE
Filter link broken

### ISSUE THREAD

**Issue by jkuelz** [sheared-sasquatch/sparkclips#56]
When I hover over the word filter on the bottom left, the cursor changes, making me think it would be a clickable link, however when I try and click on it, nothing happens. Additionally, the tag icon on the bottom right brings up a list of filterable items but when I check some of those and then close the filter, the data is unchanged on the gallery.
1. click tag icon
2. checked "(with facial hair)"
3. clicked the tag icon again
4. selected the first image in the gallery "Messy Medium for Straight/Wavy Hair (9 likes)"
5. the only tags on that were "(long hair) (straight hair) (low maintenance)".
Not sure the filter feature is working as it should.

**Comment by luisnaranjo733** [comment]
Removed the filter text so as to remove the possibility of future confusion
