### ISSUE TITLE
Log-Entry Detail Haircut Instructions Formatting

### ISSUE THREAD

**Issue by KyleIWS** [sheared-sasquatch/sparkclips#57]
Text area presented for haircut instructions, but newlines are not actually inserted.

**Comment by KyleIWS** [comment]
![screen shot 2017-06-07 at 3 09 15 pm](https://user-images.githubusercontent.com/19737092/26903707-4d479c3e-4b93-11e7-9cdf-75b239acf302.png)
![screen shot 2017-06-07 at 3 08 59 pm](https://user-images.githubusercontent.com/19737092/26903709-4ea66362-4b93-11e7-8eae-25926b021b46.png)

**Comment by KyleIWS** [comment]
Above images show the problem in more detail.

**Comment by Nate-Swanson** [comment]
Fixed text box to display single line so users won't add line breaks and expect them to show up in the details page.
